### PR TITLE
Add Ur16e support

### PR DESCRIPTION
**Pull request by fmauch**
This PR aims at adding ur16e support to `univeral_robot`.

This basically implements #460  and UniversalRobots/Universal_Robots_ROS_Driver#73.

It is built upon #371 and #414 so it will have parametrized xacro files and support for robot calibration.

The current status:

 - [x] Add config files for ur16e
 - [x] Add description launch files for ur16e
 - [x] Add gazebo launchfile for ur16e
 - [x] Add meshes of upper and lower arm. To my knowledge all other segments are the same as for the ur10e. The arm segments are also the same, but shortened. So, taking out a part in the middle should be sufficient.
 - [x] Update physical and visual parameters. I started working on those, but many of them are copied from the ur10e
 - [ ] Add ur_kinematics files for the ur16e
 - [ ] Add ur16_e_moveit_config

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@fmauch: would you already want to get this merged into `melodic-devel-staging`, or would you want to finish the last two items in your list?

I'd be OK with merging this as-is. I'll rebase it on-top of `melodic-devel-staging` in that case (similar to #495).

**Comment by fmauch** [comment]
As I'm not very familiar with those two points, I'd be fine with leaving them for a later PR.

Edit:
But it might make sense to merge #495 first and rebase this ontop if that, as this is already with the calibration correction built-in.

**Comment by gavanderhoorn** [comment]
> As I'm not very familiar with those two points, I'd be fine with leaving them for a later PR.

Ok.

> But it might make sense to merge #495 first and rebase this ontop if that, as this is already with the calibration correction built-in.

Yes, that is the plan.

**Comment by fmauch** [comment]
Rebased this PR

**Comment by gavanderhoorn** [comment]
Continued in #496.

**Comment by gavanderhoorn** [comment]
> Rebased this PR

Apologies @fmauch, I didn't see your comment.

I've opened #496, which is essentially the same.

**Comment by gavanderhoorn** [comment]
Would you want us to continue with this one?

Full attribution of the commits is preserved in #496.

**Comment by gavanderhoorn** [comment]
Merging this without waiting for Travis as we already know this passes CI (from #496).

**Review by gavanderhoorn — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Thanks @fmauch :+1:

**Comment by hellohake** [comment]
Hello, I am doing some research on UR16E now.May I ask where can I get the accurate inertia parameters of ur16e now ? and when can the official configuration of UR16_e_moveit_config be released.  Thanks~

**Comment by hellohake** [comment]
Hello, I am doing some research on UR16E now.May I ask where can I get the accurate inertia parameters of ur16e now ? and when can the official configuration of UR16_e_moveit_config be released. Thanks~

**Comment by hellohake** [comment]
Hello, I am doing some research on UR16E now.May I ask where can I get the accurate inertial parameters of ur16e now ? and when can the official configuration of UR16_e_moveit_config be released. Thanks~

**Pull request merged**
