### PR TITLE
RobotStateRT V15 added to indigo_dev

### PR DESCRIPTION
**Pull request by jeppewalther**

### CODE REVIEW

**Comment by fmessmer** [comment]
@jeppewalther 
Thanks, this implements the revision 4 of the RealTimeProtocol, right?
So this is tested on a UR 5 v1.5?
Does this work with a v1.4, too?

Looks good to me! Also, does not conflict with other controller versions!

**Comment by tnl-woi** [comment]
:+1:

**Comment by jeppewalther** [comment]
I have not tested on v1.4. It is working with the CB1 next to me with v1.5.

**Comment by jeppewalther** [comment]
And yes this is based on revision 4 of the RealTimeProtocol.

**Comment by abubeck** [comment]
As all agree, I will merge this in.

**Pull request merged**
