### PR TITLE
readme: add license badge

### PR DESCRIPTION
**Pull request by hsd-dev**
Related to https://github.com/ros-industrial/ros_industrial_issues/issues/57

### CODE REVIEW

**Review by gavanderhoorn — DISMISSED** [review]
Thanks :+1:

**Comment by gavanderhoorn** [comment]
I've added one commit that adds the Apache v2 badge: `ur_kinematics` contains Apache licensed code.

**Review by miguelprada — APPROVED** [review]
:+1:

**Comment by gavanderhoorn** [comment]
Thanks for the review @miguelprada and thanks for the PR @ipa-hsd.

**Pull request merged**
