### PR TITLE
enabled to use effort controller with 'use_effort_controller'

### PR DESCRIPTION
**Pull request by k-okada**
This reverts #161, I understand the motivation listed on #161, but position control will produce unstable motion when the robot contacts with object/environment, this is more stable for such situation.

### CODE REVIEW

**Comment by k-okada** [comment]
Testing with this script;

```
#!/usr/bin/env python

import rospy
import actionlib
from control_msgs.msg import FollowJointTrajectoryAction, FollowJointTrajectoryActionGoal, FollowJointTrajectoryGoal
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint

rospy.init_node('send_motion')
rospy.sleep(1)

client = actionlib.SimpleActionClient('arm_controller/follow_joint_trajectory', FollowJointTrajectoryAction)
client.wait_for_server()

msg = FollowJointTrajectoryActionGoal()
msg.goal_id.id = 'id'
msg.goal_id.stamp = rospy.get_rostime()
msg.goal.trajectory.header.stamp = rospy.Time.now() + rospy.Duration(0.2)
msg.goal.trajectory.joint_names = ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']
msg.goal.trajectory.points.append(JointTrajectoryPoint(positions=[0,0,0,0,0,0], time_from_start = rospy.Duration(1)))
msg.goal.trajectory.points.append(JointTrajectoryPoint(positions=[0,-1.5704,0,0,0,0], time_from_start = rospy.Duration(2)))
msg.goal.trajectory.points.append(JointTrajectoryPoint(positions=[0,-1.5704,0,0,0,0], time_from_start = rospy.Duration(3)))
msg.goal.trajectory.points.append(JointTrajectoryPoint(positions=[0,-0.5236,1.0472,-0.5326,0,0], time_from_start = rospy.Duration(4)))
msg.goal.trajectory.points.append(JointTrajectoryPoint(positions=[0,-0.5236,1.0472,-0.5326,0,0], time_from_start = rospy.Duration(5)))
msg.goal.trajectory.points.append(JointTrajectoryPoint(positions=[0,0,1.5704,0,0,0], time_from_start = rospy.Duration(6)))
client.send_goal(msg.goal)
client.wait_for_result()

```

**Comment by k-okada** [comment]
i have changed my mind, added xacro interface to use effort_interface if you like, default behavior has not been changed. 

```
+  <xacro:arg name="use_position_interface" default="true" />
+  <xacro:arg name="use_effort_interface" default="false" />
```

**Comment by shaun-edwards** [comment]
@k-okada, thanks for this contribution.  Sorry it took us so long to respond.  We aim to be better from here on out.  
@ThomasTimm, can you look at this one.  I don't have experience with the `HardwareInterface` functionality.

**Comment by ThomasTimm** [comment]
To my knowledge it is not possible to control the joint effort on the UR and as such, I'm not sure it makes much sense to implement a `EffortJointInterface` in the URDF, seeing that the UR controller does not expose such an interface. Thus users might find themselves spending valuable time developing a solution that works in simulation, only to find that it can't be used on a real robot.

It might be possible to hack a Cartesian-based effort interface together, but I am not sure how well that would work. Also, I haven't heard of a `EffortCartesionInterface` in ROS yet, just as I haven't heard of UR planning to expose a joint effort interface. But my sources for that isn't any better than what is publicly available.

On the other hand, implementing a `VelocityJointInterface` in the URDF would make a lot of sense as that is supported by the controller and already implemented in the ur_modern_driver

**Comment by gavanderhoorn** [comment]
The way this change is implemented would seem to be fully bw-compatible, so we could potentially merge this.

The PR does however seem to include e586420c2d85b907351c4d9faf68af531dbdbd91, which is part of #226. It would be good if we could keep these changes separate.

@k-okada: is this something you think would be possible? Let me know, otherwise I'll create a version of this PR without e586420c2d85b907351c4d9faf68af531dbdbd91.

**Comment by gavanderhoorn** [comment]
We could probably simplify the PR quite a bit by making use of Jade+ xacro with default arguments (and then making the `hardwareInterface` value a property). That would probably allow us to avoid the many `if-else` repeats.

**Comment by k-okada** [comment]
@gavanderhoorn yes, using effort controller and changing inertial values can be separated. But I think effort controller requires better inertial modeling... so  I think it better to merge #226 first.

**Comment by nag92** [comment]
Will the effort controller work on real hardware?

**Comment by gavanderhoorn** [comment]
@nag92: no, this is just for simulation.

UR does not expose a joint torque control interface.

**Comment by gavanderhoorn** [comment]
Related: #521.

**Comment by fmauch** [comment]
Closing this in favor of #619

I guess, targeting indigo-devel is not relevant anymore...

**Pull request closed without merging**
