### PR TITLE
Replace __ prefixes

### PR DESCRIPTION
**Pull request by fmauch**
With newer versions of xacro this leads to errors otherwise.

Also see https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/463 and https://github.com/ros/xacro/commit/9941961b2ac5eb91822c6c50c251ed094af24d6b

### CODE REVIEW

**Comment by danielcranston** [comment]
Is there anything preventing this from being merged? As I see it `melodic-devel-staging` is basically broken (processing any robot with `xacro` will fail) until this is merged.

**Comment by gavanderhoorn** [comment]
This is already fixed in [fmauch/universal_robot](https://github.com/fmauch/universal_robot), which is the version which should be used with `UniversalRobots/Universal_Robots_ROS_Driver`.

**Comment by danielcranston** [comment]
>  [fmauch/universal_robot](https://github.com/fmauch/universal_robot), which is the version which should be used with `UniversalRobots/Universal_Robots_ROS_Driver`.

Unfortunately `UniversalRobots/Universal_Robots_ROS_Driver` seems to be of a different opinion:
https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/.melodic.rosinstall#L4

Could you link to where it's explained that the fmauch fork is the intended version? (I thought the rosinstall file was the source of truth)

**Comment by gavanderhoorn** [comment]
See https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/463 and https://github.com/fmauch/universal_robot/issues/18.

**Comment by fmauch** [comment]
> > [fmauch/universal_robot](https://github.com/fmauch/universal_robot), which is the version which should be used with `UniversalRobots/Universal_Robots_ROS_Driver`.
> 
> Unfortunately `UniversalRobots/Universal_Robots_ROS_Driver` seems to be of a different opinion:
> https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/.melodic.rosinstall#L4
> 
> Could you link to where it's explained that the fmauch fork is the intended version? (I thought the rosinstall file was the source of truth)

I am about to create a PR for the driver using my fork again. Sorry for the current situation, we hope to straighten the UR support situation soon.

**Pull request merged**
