### PR TITLE
ur_gazebo: remove run_depend on gazebo_ros_pkgs meta pkg

### PR DESCRIPTION
**Pull request by achim-k**
Causing build error:
`Abandoned <<< ur_gazebo                                                            [ Depends on unknown jobs: gazebo_ros_pkgs ]`

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Looks like `ur_gazebo` depends on a metapackage (`gazebo_ros_pkgs`) which isn't allowed and causes `catkin_tools` to not build `ur_gazebo`. This is a known issue (?) with `catkin_tools`, but `ur_gazebo` shouldn't depend on metapackages in the first place.

The proposed change however only removes the metapackage reference. @achim-k: could you make sure that `ur_gazebo`'s dependencies are now still sufficiently documented? We'd probably need to add some other dependencies.

**Comment by achim-k** [comment]
I checked all nodes that are launched and all dependencies seem to be satisfied. For completeness I added a run_depend on `controller_manager` although it should already be satisfied by depending on `gazebo_ros_control`.

**Comment by gavanderhoorn** [comment]
Thanks for checking @achim-k.

Appreciated.

**Review by gavanderhoorn — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
This is merged in 0c34123c779d4076a75acf892571f8ec4aa018cc.

Thanks for contributing @achim-k, much appreciated.

**Pull request closed without merging**
