### PR TITLE
RobotStateRT V15 added to hydro_dev

### PR DESCRIPTION
**Pull request by jeppewalther**

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@jeppewalther: nice. Thanks for the contribution. Before we review this, could I ask you to squash all 3 commits into 1? Seeing as the last two are fixup commits.

**Comment by fmessmer** [comment]
see also my comments in #153 

Besides squashing...this should be good for merge...

**Comment by tnl-woi** [comment]
:+1:

**Comment by jeppewalther** [comment]
Squashed :)

**Pull request merged**
