### PR TITLE
description: add missing safety_ctrlr for shoulder pan.

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

I believe this was just an oversight (ie: the fact it was not added in #371), but I'd like to make sure I understand things correctly.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@ipa-led: was there a specific reason `shoulder_pan` did not get a `safety_controller` element?

**Comment by dhled** [comment]
> 
> 
> @ipa-led: was there a specific reason `shoulder_pan` did not get a `safety_controller` element?

None that come to my mind, except that I may have forget / miss a line somethere.

**Review by dhled — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Ok, thanks.

Just wanted to make sure.

**Comment by gavanderhoorn** [comment]
Thanks for the review @ipa-led :+1:

**Pull request merged**
