### PR TITLE
Issue #35 port fixes from original driver script

### PR DESCRIPTION
**Pull request by jrgnicho**
Issue #35
This changes add the workaround from the automate driver script.

### CODE REVIEW

**Comment by jrgnicho** [comment]
@shaun-edwards  please review

**Comment by shaun-edwards** [comment]
@jrgnicho - Can you tell me what testing you did in order to verify that the changes don't exhibit the behavior in issue #35.

**Comment by jrgnicho** [comment]
@shaun-edwards  - I tested the script with a  pick and place task application.  I ran this application about 10 different times and each time a slightly different trajectory was generated and executed successfully. I did not observe any of the  timeout problems produced before for not reaching the last trajectory point.  If more rigorous testing is needed please advice.

**Comment by shaun-edwards** [comment]
+1

**Pull request merged**
