### PR TITLE
Issue: classnames in driver

### PR DESCRIPTION
**Pull request by fmessmer**
this solves #2

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
This looks alright. @ipa-fxm: I assume you did, but have you tested this on real hardware?

I only did a static inspection, but +1 if you tested it.

**Comment by fmessmer** [comment]
I tested both PR #65 and #66 with a single UR10 hardware setup - setting the reverse_port to 50005.
The tab vs. spaces commit was just for beautifying, I did not get any error during testing with the hardware. I was able to move the arm and receive joint_states...What effect have you been observing?

**Comment by gavanderhoorn** [comment]
> The tab vs. spaces commit was just for beautifying

I wasn't commenting on the proper functioning of the driver, just that the indentation of the lines affected by that commit is now not correct (see [line 189](https://github.com/ipa-fxm/universal_robot/blob/ffd31dc9013855ba30eb6cd8873946379e2f9ed9/ur_driver/prog#L189) and [line 197](https://github.com/ipa-fxm/universal_robot/blob/ffd31dc9013855ba30eb6cd8873946379e2f9ed9/ur_driver/prog#L197) for instance).

**Comment by fmessmer** [comment]
I guess the tab vs. spaces did not matter too much as the UR script uses 'end' for all the control structures. Anyway, I tried to fix the indentation. 
@gavanderhoorn can you review whether it is correct now?

**Comment by gavanderhoorn** [comment]
indentation looks fine. I agree it is mostly cosmetic, but my internal parser isn't happy otherwise :). Also it helps spotting logic errors.

thanks. Looks good now.

**Pull request merged**
