### PR TITLE
Calibrated URDF (rebased on-top of melodic-devel-staging)

### PR DESCRIPTION
**Pull request by gavanderhoorn**
This is @fmauch's work but rebased on-top of `melodic-devel-staging`.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@fmauch: I'm going to merge this, but you may have updates or fixes you'd want to contribute.

We can do that in a follow-up PR.

**Comment by fmauch** [comment]
There definitely are things I'd like to update. But merging this and making a separate PR is fine with me :-)

**Comment by gavanderhoorn** [comment]
Thanks @fmauch for the contribution :+1:

**Comment by gavanderhoorn** [comment]
I botched up the author<->committer, so force-pushed a fix.

Commit is now 9245b382.

**Pull request merged**
