### PR TITLE
Updated mesh ambience so the model isn't so dark in gazebo

### PR DESCRIPTION
**Pull request by dniewinski**

### CODE REVIEW

**Comment by dniewinski** [comment]
Are you waiting on me for anything for this?  It is just a minor cosmetic update

**Comment by ipa-nhg** [comment]
:+1:  Nice!

Before:
screenshot from 2018-09-06 13-28-00

After:
screenshot from 2018-09-06 13-30-36

@dniewinski Thanks a lot!

**Review by ipa-nhg — APPROVED** [review]

**Comment by dovanhuong** [comment]
Dear @ipa-nhg,

 I'm having a problem with command "roslaunch ur_gazebo ur5.launch" with error: "no p gain specified for pid ..." 

the detail of issue as the link: https://github.com/dovanhuong/universal_robot_issue_ur_gazebo_ur5.launch

Could you please take a look on it and give me your advices!

Sincerely yours,

**Comment by gavanderhoorn** [comment]
I'm sorry @dovanhuong, but you already posted this in https://github.com/ros-industrial/universal_robot/issues/397.

Please do not post comments on random / unrelated other issues.

If no-one has responded to your issue, either no one knows, or no one has had time to look into your issue yet.

Please keep all discussion on your own issue (ie: https://github.com/ros-industrial/universal_robot/issues/397).

**Comment by sapan-ostic** [comment]
@ipa-nhg How was the problem solved?

**Comment by gavanderhoorn** [comment]
@sapan-ostic: which problem? This PR was merged.

**Pull request merged**
