### PR TITLE
WIP: Upgrade MoveIt new KinematicBase API

### PR DESCRIPTION
**Pull request by davetcoleman**
@rhaske updated the kinematics API in Melodic, this fixes deprecation warnings

> ros.moveit_core.kinematics_base: IK plugin for group 'manipulator' relies on deprecated API. Please implement initialize(RobotModel, ...).

I also submitted this here: https://github.com/fmauch/universal_robot/pull/3

### CODE REVIEW

**Comment by davetcoleman** [comment]
This is WIP because I made a fix in this other PR that needs to be copied over here (once that's merged):
https://github.com/fmauch/universal_robot/pull/3

Having multiple used forks is very complicated...

**Comment by gavanderhoorn** [comment]
It would probably have been sufficient to just submit the PRs here.

@fmauch  could then rebase his branch and things would've worked out.

**Comment by davetcoleman** [comment]
I submitted the PR to the branch used by the official UR driver, which seems to carry more weight than this repo.

Thanks for responding to https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/84

**Comment by gavanderhoorn** [comment]
> I submitted the PR to the branch used by the official UR driver, which seems to carry more weight than this repo.

I'm not sure I follow this.

It's also not true.

**Comment by fmauch** [comment]
> @fmauch could then rebase his branch and things would've worked out.

I'd like to avoid rebasing the branch being used for the driver currently, as from my experience people not too familiar with git will get confused if they can't do a normal `git pull`. But performing a normal merge would be fine, for sure :-)

So, in fact, I will vote for merging those here, as well.

**Comment by davetcoleman** [comment]
> It's also not true.

I'm referring to the ``master`` README of https://github.com/UniversalRobots/Universal_Robots_ROS_Driver 

Where it says:
```
# clone fork of the description to use the calibration feature
$ git clone -b calibration_devel https://github.com/fmauch/universal_robot.git src/fmauch_universal_robot
```

We are using the new (OEM) UR driver and thus, using this fork. Based on past experience of the ur_modern_driver, I know it can take years to sort out forking of UR-related repositories and so I have no confidence that https://github.com/ros-industrial/universal_robot/ is relevant anymore.

However, I know the current situation is not ideal so I've created PRs to both locations in attempt to do the best thing possible.

**Comment by davetcoleman** [comment]
@fmauch I think a merge in the branch will be hard to rectify in the future, or at least be ugly in the commit history

Maybe we should just wait before merging my PRs until the calibration branch is sorted out. How long will that be? Having end-users work from a feature branch is really not ideal for the reasons your just outlined.

**Comment by gavanderhoorn** [comment]
> so I have no confidence that https://github.com/ros-industrial/universal_robot/ is relevant anymore.

Ok.

**Comment by ljden** [comment]
What's the status of this?

**Comment by fmauch** [comment]
Since the changes from this PR seem to make the plugin crash, I'll remove it from the milestone. Changing this after the first binary release should not be much of an issue.

**Comment by simonschmeisser** [comment]
The crash is due to robot_model_ in the plugin shadowing the "newly" * introduced robot_model_ in KinematicsBase, sorry for not opening a PR earlier

* newly as in a looong time ago :wink:

**Comment by fmauch** [comment]
Closing this in favor of #644

**Pull request closed without merging**
