### PR TITLE
Fix elbow joint limits

### PR DESCRIPTION
**Pull request by beatrizleon**
We want to propose this PR that will fix the joints limits of the elbow joint according with the results discussed in https://github.com/ros-industrial/universal_robot/issues/265 for the ur10 and ur5

### CODE REVIEW

**Comment by v4hn** [comment]
@ipa-fxm @gavanderhoorn This issue has been raised and analyzed **a year ago**.
**Please merge&release at least** #302 to get this fixed in kinetic.
There is still no official driver available for kinetic (the rewritten driver is still pending), so I believe it is well-justified to merge this into indigo too.

Today I talked to one more PhD student who fell into this trap last year and the lab decided not to use MoveIt! after trying for some time. This is the second time I hear about something like that.
This is awful and bad advertisement for Motion Planning in ROS.

**Comment by gavanderhoorn** [comment]
Not a change that CI has any tests for, so I feel it's justified to merge without waiting for Travis to complete.

**Comment by gavanderhoorn** [comment]
Thank you for taking the time to fix this @beatrizleon :100:

**Comment by gavanderhoorn** [comment]
And we should have merged this sooner :disappointed:

**Pull request merged**
