### PR TITLE
Add convenience macros for description files

### PR DESCRIPTION
**Pull request by fmauch**
Originally started by @gavanderhoorn this PR aims at providing direct xacro macros for each robot model.

This way, users can easily embed a UR robot into their own robot descriptions without the necessity of providing all xacro arguments, as default values for the respective models are already set.

I mainly open this PR, as I'd like to base #538 on top of those changes. @gavanderhoorn I hope you don't mind hijacking your efforts here.

### CODE REVIEW

**Review by ipa-nhg — APPROVED** [review]
I have tested all the URDF models, spawning all of them on simulation, visualizing the tf trees on RVIZ and moving all the joints to their limits with the joint trajectory controller. 

LGTM 👍🏽 
Thanks a lot @fmauch

**Comment by fmauch** [comment]
Sorry for bothering, but is anything holding this back?

**Comment by lianghongzhuo** [comment]
Since this pull request has been approved by a reviewer, can anyone have merge permission merge this one?

**Comment by ljden** [comment]
Bump

**Comment by dhled** [comment]
Also approving :)

**Comment by ipa-nhg** [comment]
ping @gavanderhoorn , could you please check the changes proposed here and merge the PR? I have already tested and approved it.

**Comment by ljden** [comment]
Is there any particular reason this isn't merged?

**Comment by lianghongzhuo** [comment]
Please merge this

**Comment by lianghongzhuo** [comment]
Please merge this

**Review by gavanderhoorn — APPROVED** [review]
This is a mess, but that's not @fmauch's fault.

Let's at least resolve the situation where we have nothing.

**Pull request merged**
