### PR TITLE
[Indigo] crop ik solutions wrt joint_limits

### PR DESCRIPTION
**Pull request by fmessmer**
This PR crops the ik_solutions provided by ur_kinematics wrt the joint_limits used in the `/robot_description`.
Thus, the same plugin now works for the limited version of the UR5/UR10 as well!

### CODE REVIEW

**Comment by tnl-woi** [comment]
Tested with limited joints and works fine! :+1:
As for me, the URKinematics plugin may become the default again.

**Comment by UltronDestroyer** [comment]
Does this work for unlimited?

**Comment by fmessmer** [comment]
Yes, the same plugin now works for both limited and unlimited versions!

**Comment by abubeck** [comment]
As this is tested. I will merge.

**Comment by gavanderhoorn** [comment]
@abubeck: I think @TheDash has not yet reported either success or failure (and commented on #155). Seems premature to merge this without confirmation that it works for the user who reported the issue?

**Comment by abubeck** [comment]
@gavanderhoorn : @ipa-fxm has tested it with both limited and unlimited versions.

**Comment by gavanderhoorn** [comment]
Yes, I know :). But the `URKinematics` plugin was tested in the past as well, but then it didn't work on other peoples' setups. So some additional testing wouldn't seem to be a bad thing.

**Comment by UltronDestroyer** [comment]
I just made an attempt to run the planner/solver with joint_limited:=true and false. The limited:=true makes the arm purple and only plannable by random configurations. The limited:=false never solves the freeform orb problem.

**Comment by UltronDestroyer** [comment]
Note: this has been solved.. will report later with the solution.

Edit:

The issue was a combination of the changes made regarding the hardware interface and the delay of a package release.

I had used the deb package of UR which didn't have the kinematic planner changes to allow free planning motion. That didn't work, and I tried installing the source package instead. the source package however wasn't compatible with the controller interface for Gazebo that I had specified, and it wasn't reporting an error. Once I downloaded and used the universal_robot package from source, and changed my gazebo controller interface to be position_controllers, everything worked fine.

**Comment by fmessmer** [comment]
@TheDash 
True, this feature is not yet released....also see my comments in #202

**Comment by UltronDestroyer** [comment]
Right, it should be released because using things from source on all of the platforms/tutorials that I have put out can be problematic for users. For example, when I tried to install code on one of our platforms, to my dismay, I had to find out that you guys changed the hardware interface which affected the simulator and took me about 8 hours to fix. The only way I found that this was the actual change was by reading through the code commits on your personal fork of the project. 

Not only that, but the UR5KinematicsPlugin requires the joint configuration to be unlimited, and the MoveIt configurations requires the URDF to have it specified as the limited configuration so it is really confusing for myself and users.

When you re-release this package, can we somehow notify everyone that uses the UR5 arm in gazebo that their simulators will no longer work and tell them what the fix is? (E.g telling their configs to use position_controllers/PositionJointInterface). I only found that out by reading a commit message, which is shrouded away in the forests of github.

**Comment by achim-k** [comment]
With this PR being merged, is there still a reason not to set the default IK-plugin back to `ur_kinematics/URXKinematicsPlugin`. The default was set to KDLPlugin in https://github.com/ros-industrial/universal_robot/pull/128
Sorry to bring this up again

**Pull request merged**
