### PR TITLE
Fix overlapping properties + allow namespacing

### PR DESCRIPTION
**Pull request by dhled**
Include PR: https://github.com/ros-industrial/universal_robot/pull/356 from @felixvd

Added a ur.common.xacro file for common macro
Made the include part of the macro to allow namespacing
Checked that xacro produce the same file for both with "--inorder" or without.

Issue : https://github.com/ros-industrial/universal_robot/issues/271

### CODE REVIEW

**Review by ipa-nhg — DISMISSED** [review]
Tested on simulation :+1:

**Comment by Chamango90** [comment]
Reviewed and accepted

**Comment by gavanderhoorn** [comment]
@ipa-led: similar to #371, this needs a rebase and fixup of the conflicts.

**Comment by dhled** [comment]
Can be closed, changes already done in this one https://github.com/ros-industrial/universal_robot/pull/356

**Pull request closed without merging**
