### PR TITLE
Ur3 moveit config

### PR DESCRIPTION
**Pull request by fmessmer**
Provide a moveit_config for the UR3

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
I've played around a bit with this (using ur-sim) and this seems to work correctly.

There are quite some non-bw-compatible changes in these PRs though (mesh renaming, removal of urdfs/xacros, etc).

**Comment by fmessmer** [comment]
Thanks for the review.
What URSim version (3.X.YYYY) did you use for testing? Did it work with the `ur_driver` from this feature-branch/PR? (Haven't tested it myself....gazebo only :wink:)

Yes, I made these changes on purpose...for the sake of consistency, reusability and simplicity!
No one ever used the transmission/gazebo.xacro files standalone, i.e. separate from urX.urdf.xacro as well as no one uses the urdfs...

**Comment by gavanderhoorn** [comment]
@ipa-fxm wrote:

> Thanks for the review.

well, I wouldn't call it a review .. I've played with it :).

> What URSim version (3.X.YYYY) did you use for testing? Did it work with the ur_driver from this feature-branch/PR? (Haven't tested it myself....gazebo only :wink:)

I actually used ursim-1.8, as that was what I had on my machine. Everything is in joint space, so a UR5 can stand-in for a UR3.

> Yes, I made these changes on purpose...for the sake of consistency, reusability and simplicity!
> No one ever used the transmission/gazebo.xacro files standalone, i.e. separate from urX.urdf.xacro as well as no one uses the urdfs...

As far as you know :). Cleaning up is ok, I'm just careful to never assume anything about my users when making changes to pkgs.

**Comment by fmessmer** [comment]
Well, I take the blame on me then...

I'll hold this for a bit longer, but I'm tempted to merge it as it is quite soon(most likely as soon as I'll find the time to work with the UR again)

**Comment by fmessmer** [comment]
I'm going to merge all UR3 related PRs now as they have been open long enought!

**Pull request merged**
