### PR TITLE
Update base.dae

### PR DESCRIPTION
**Pull request by leitoxve**
light delete

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Thanks for the PR.

Could you check whether #575 does the same thing?

**Comment by leitoxve** [comment]
NOO!! @gavanderhoorn 
hahahhahaha I'm kidding, give me a little more time 1 day and I check the UR10 UR5 and UR3
but count on that.
is time of "Apéro" in the French time zone!! xD

**Comment by gavanderhoorn** [comment]
@leitoxve: what's the status here :)

And please could you explain what your PR will fix?

**Comment by dhled** [comment]
I guess this is duplicating with #575

As #575 is more advanced I think we can close this one.

**Pull request closed without merging**
