### PR TITLE
msgs: clarify use of fields in SetIO svc

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Triggered by [UR10 tool flange 24V power control](https://answers.ros.org/question/320110) on ROS Answers.

**Review by miguelprada — APPROVED** [review]
Nice, thanks @gavanderhoorn!

**Comment by miguelprada** [comment]
Will merge when the tests pass.

It makes me think whether `ur_modern_driver` should use `std::lround` instead of `static_cast<uint8_t>` to [transform tool voltages](https://github.com/ros-industrial/ur_modern_driver/blob/7fae9f236e9557eb09e5e6554abe54da9de8f24a/include/ur_modern_driver/ros/io_service.h#L53) just to be safer.

**Comment by gavanderhoorn** [comment]
> It makes me think whether `ur_modern_driver` should use `std::lround` instead of `static_cast<uint8_t>` to [transform tool voltages](https://github.com/ros-industrial/ur_modern_driver/blob/7fae9f236e9557eb09e5e6554abe54da9de8f24a/include/ur_modern_driver/ros/io_service.h#L53) just to be safer.

It should at the very least probably check whether `state in [0, 12, 24]`.

But yes, that would make sense.

Can you log an issue over at `ros-industrial/ur_modern_driver`?

**Pull request merged**
