### PR TITLE
Reduce longest valid segment fraction to accomodate non-limited version of the UR5

### PR DESCRIPTION
**Pull request by scottpaulin**
0.01 is the value suggested by @davetcoleman. It looks like it works well for self-collisions. Some users may need to reduce this value if they have very small or thin obstacles.

@davetcoleman what are your thoughts on this?

### CODE REVIEW

**Comment by davetcoleman** [comment]
Like I said before, its a simple tradeoff between computation time and the possibility of missing collisions. But it also depends on the size of your obstacles - I think this value is good and even think we should make it the default for future robot config packages: https://github.com/ros-planning/moveit/blob/091f766175fadb1fd4cdab405715237cfdc88f80/moveit_setup_assistant/src/tools/moveit_config_data.cpp#L409

**Comment by gavanderhoorn** [comment]
Again a change for which no CI coverage is available.

**Comment by gavanderhoorn** [comment]
Tested this locally. On even a moderately specced machine, I do not experience a significant difference between the current value (`0.05`) and the proposed one (`0.01`).

As there is consensus that decreasing the value is beneficial - and not only when planning with the non-joint-limited version of the urdfs - I'm merging this.

**Comment by gavanderhoorn** [comment]
And bp to Indigo.

**Comment by gavanderhoorn** [comment]
And I forgot: thanks a bunch @scottpaulin for digging into the issues with the elbow and proposing this change to `longest_valid_segment_fraction`. :beers:

**Pull request merged**
