### PR TITLE
Load the JointGroupPositionController so jog commands can be sent

### PR DESCRIPTION
**Pull request by AndyZe**
I would like this so I can finish a jogging tutorial based on the UR3 in Gazebo

### CODE REVIEW

**Comment by AndyZe** [comment]
I guess it would make sense to add the same for UR5/UR10, too, right?

**Comment by gavanderhoorn** [comment]
> I guess it would make sense to add the same for UR5/UR10, too, right?

That does make sense, but then it would also make sense to load the controllers. The current PR only does that for the UR3.

**Comment by mlautman** [comment]
looks good to me

**Comment by AndyZe** [comment]
@gavanderhoorn @ipa-nhg @miguelprada Not to pressure/stress you, but this is the last call before I move forward with a different Gazebo robot

**Review by miguelprada — CHANGES_REQUESTED** [review]
Sorry for the delayed response.

The addition of the new controller demands `position_controllers` to be declared as a `run_depend` in the package manifest.

Also, for completeness sake, it'd be good to replicate the changes in `ur_e_gazebo` (don't forget the dependency there as well).

**Review by miguelprada — APPROVED** [review]

**Comment by miguelprada** [comment]
Looks good to me. @gavanderhoorn, @ipa-nhg could you give it a second look and merge if you're ok with it?

**Review by mlautman — APPROVED** [review]

**Review by gavanderhoorn — APPROVED** [review]
Might be nice to sync the `ros_control` configs for the real robot and the Gazebo ones, but this is OK for now.

**Comment by gavanderhoorn** [comment]
@miguelprada: feel free to merge.

**Comment by gavanderhoorn** [comment]
And please squash merge. The fixups don't need to become part of the history.

**Comment by miguelprada** [comment]
Thanks for iterating and for your patience @AndyZe!

**Pull request merged**
