### PR TITLE
F#src 4095 fixing deprecation msgs

### PR DESCRIPTION
**Pull request by mikramarc**
Removing deprecated parameter

https://github.com/ros-planning/moveit/blob/melodic-devel/MIGRATION.md

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Did you intend to submit this to the ShadowRobot fork instead?

**Comment by mikramarc** [comment]
Hi @gavanderhoorn No. This parameter is deprecated in new moveit melodic version and is going to cause deprecation warnings, I assume you would like this change in your repository as well.

**Comment by gavanderhoorn** [comment]
Thanks for submitting the PR in that case :100: 

However, I believe this is a duplicateof #474 in this case.

**Comment by mikramarc** [comment]
True, I missed that, sorry about that :) Closing it.

**Comment by gavanderhoorn** [comment]
No problem.

Thanks for submitting yours :)

**Pull request closed without merging**
