### PR TITLE
Add optional safety_controller tags to all joints in xacro macros

### PR DESCRIPTION
**Pull request by ipa-nhg**
Update and supersede https://github.com/ros-industrial/universal_robot/pull/349

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@ipa-nhg: did this add support for e-series as the main difference with #349?

**Comment by gavanderhoorn** [comment]
This is a rebase only, correct @ipa-nhg ?

**Review by miguelprada — CHANGES_REQUESTED** [review]
Can you extend the changes to `ur_e_description`?

**Comment by ipa-nhg** [comment]
It was a cherry-pick a commit and rebase to kinetic an old (with merge conflict) PR .

Now I extended this to the e-series. I tested on simulation that the urdfs are not broken

**Review by miguelprada — APPROVED** [review]
Thanks @ipa-nhg!

**Comment by jrgnicho** [comment]
All moveit_config demos work, thanks for the contribution

**Review by jrgnicho — APPROVED** [review]

**Pull request merged**
