### PR TITLE
Fix UR5 namespace of params for trajectory_execution

### PR DESCRIPTION
**Pull request by ljmljz**
Fix UR5 namespace of params for trajectory_execution. It also refer the issue #307

### CODE REVIEW

**Comment by fmessmer** [comment]
should be obsolete with #309

**Comment by fmessmer** [comment]
@ljmljz 
as I merged #309, rebasing your branch `ljmljz:param-traj-execution` should result in an empty PR..

**Comment by ljmljz** [comment]
Thanks for your reply. I saw the changing has been merged #309.

**Comment by gavanderhoorn** [comment]
As @ipa-fxm determined, this was fixed by #309. Closing this one.

Still: tnx for making the effort to submit the PR @ljmljz :+1:

**Pull request closed without merging**
