### PR TITLE
Moveit issues hydro

### PR DESCRIPTION
**Pull request by fmessmer**
This PR builds on top of #121 and #122 
It adds new collision meshes for the UR10 (simplified stl's). Number of vertices for UR10 collision meshes are about the same as for UR5 collision meshes.
It also re-generates the urX_moveit_configs (i.e. self-collision-matrix!)
It makes the KDLKinematicsPlugin the default IK-Plugin again, as the ur_kinematics plugins fail for joint_limited versions of UR5 and UR10 respectively.
It also re-generates the URDF files from the latest XACRO files

### CODE REVIEW

**Comment by fmessmer** [comment]
Since #121 and #122 have been accepted, I did a rebase.
Please test this PR with UR5/UR10 and provide feedback!
@hersh @tnl-woi @gavanderhoorn @shaun-edwards

**Comment by gavanderhoorn** [comment]
On 22-10-2014 12:44, Felix Messmer wrote:

> Since #121 and #122 have been accepted, I did a rebase.
> Please test this PR with UR5/UR10 and provide feedback!
> @hersh @tnl-woi @gavanderhoorn @shaun-edwards 

I'll not be in a position to test until late next week.

**Comment by hersh** [comment]
+1.  I ran demo.launch in ur5_moveit_config and ur10_moveit_config from this pull request and checked the collision behavior, which looks correct.

Thanks Felix!

**Comment by UltronDestroyer** [comment]
Does the Rviz demo work yet? Mine complains about controllers.

```
"Unable to identify any set of controllers that actuate the specified joints"
```

**Comment by hersh** [comment]
I ran demo.launch from the two moveit_config packages, but did not run it with the real robots.  I don't know if I got any complaints about controllers because I wasn't looking at the terminal output.  The graphical model behaved correctly.  I would be surprised if these model changes had any connection to the joint controllers.

**Comment by UltronDestroyer** [comment]
I just followed the readme here and ran the 3 commands (ur_gazebo, ur10_moveitconfig and ur10 for rviz) https://github.com/ros-industrial/universal_robot and I received this error

"Unable to identify any set of controllers taht can actuate the specified joints"

**Comment by UltronDestroyer** [comment]
The model neither moved

**Comment by fmessmer** [comment]
@TheDash 
In your case Moveit! cannot connect to the FollowJointTrajectory action.
This is because the namespaces for this action are different in simulation and the real hardware (ur_driver).
To resolve this, you should use 
`roslaunch ur5_moveit_config ur5_moveit_planning_execution.launch sim:=true`

It's documented in the README, but I admit it's probably a little confusing...I updated the Wiki in #131 in order to make it more clear!

**Comment by UltronDestroyer** [comment]
I've fixed it now. I needed to have the moveit dependencies and also inside
the controllers.yaml file add a type: FollowJointTrajectory

I'll make a PR soon.

On Thu, Oct 23, 2014 at 4:52 AM, Felix Messmer notifications@github.com
wrote:

> @TheDash https://github.com/TheDash
> In your case Moveit! cannot connect to the FollowJointTrajectory
> controller.
> This is because the namespaces for this action are different in simulation
> and the real hardware (ur_driver).
> To resolve this, you should use
> roslaunch ur5_moveit_config ur5_moveit_planning_execution.launch sim:=true
> 
> It's documented in the README, but I admit it's probably a little
> confusing...I updated the Wiki in #131
> https://github.com/ros-industrial/universal_robot/pull/131 in order to
> make it more clear!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-industrial/universal_robot/pull/128#issuecomment-60210000
> .

## 

Devon Ash
<a href="http://ca.linkedin.com/pub/devon-ash/48/478/981"
style="text-decoration:none;"><span style="font: 80% Arial,sans-serif;
color:#0783B6;">View Devon Ash's LinkedIn profileView Devon Ash's profile</span></a>

**Comment by tnl-woi** [comment]
@ipa-fxm Thanks. I've tested #130 on the UR5, see my comments there. Since that contains the same changes, I assume #128 is okay too.

**Comment by fmessmer** [comment]
I added a material (LightGrey) to the visual tags in the urdfs in order to avoid the default color `red` for the collision meshes in rviz as suggested in #130

**Comment by abubeck** [comment]
This was tested and feedback has been integrated.

**Pull request merged**
